Make deploy script shrinkwrap packages

diff --git a/deploy/deploy b/deploy/deploy
--- a/deploy/deploy
+++ b/deploy/deploy
@@ -1,10 +1,18 @@
 #!/bin/sh
 
 if $(git diff --quiet); then
+  echo "Updating and shrinkwrapping packages..."
+  (cd editor && npm shrinkwrap) || exit 1
+  (cd api && npm shrinkwrap) || exit 1
+  (cd url-fetcher && npm shrinkwrap) || exit 1
+  (cd data-store && npm shrinkwrap) || exit 1
+  git add */npm-shrinkwrap.json || exit 1
+  git commit -m 'Update and shrinkwrap packages for deploy' # if it fails, nothing has changed
+
   echo "Compiling editor assets for production..."
   (cd editor && gulp prod) || exit 1
   git add -A editor/dist || exit 1
-  git commit -m 'Recompile assets for deploy' # if it fails, that's because nothing changed
+  git commit -m 'Recompile editor assets for deploy' # if it fails, nothing changed
 
   git push origin master          || exit 1 # if everyone does this every time...
   git push truthmaker HEAD:master || exit 1 # ... this (the actual deploy) should be fast-forward
